# In .streamlit/secrets.toml
[firebase_config]
apiKey = "AIzaSyCFuqurhN5imhKDYgt_q0bD985lJ5S3BG4"
authDomain = "recipe-62441.firebaseapp.com"
projectId = "recipe-62441"
storageBucket = "recipe-62441.firebasestorage.app"
messagingSenderId = "44298467569"
appId = "1:44298467569:web:bfb0e01d27ad198f4ad150"



