name: Deploy with Firebase

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Set up Firebase Key
        run: |
          # Create directory for credentials
          mkdir -p ~/.config/firebase
          
          # Write key with proper JSON formatting
          echo '${{ secrets.FIREBASE_KEY }}' > ~/.config/firebase/key.json
          
          # Set environment variable
          echo "GOOGLE_APPLICATION_CREDENTIALS=~/.config/firebase/key.json" >> $GITHUB_ENV
          
          # Verify
          ls -la ~/.config/firebase/
          head -n 3 ~/.config/firebase/key.json

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python Script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ~/.config/firebase/key.json
        run: |
          python app.py

      - name: Deploy to Firebase
        run: |
          firebase use --token "${{ secrets.FIREBASE_TOKEN }}"
          firebase deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}"