name: Deploy with Firebase

on:
  push:
    branches: [ main ]  # Runs on push to main branch
  workflow_dispatch:    # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js (required for Firebase CLI)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Set up Firebase Key
        run: |
          echo '${{ secrets.FIREBASE_KEY }}' > firebase-key.json
          # Debug (optional)
          ls -la firebase-key.json
          head -n 2 firebase-key.json
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install all dependencies
        run: |
          pip install -r requirements.txt


      - name: Run Python Script
        run: python app.py

      - name: Deploy to Firebase
        run: |
          firebase use --token "${{ secrets.FIREBASE_TOKEN }}"
          firebase deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}"